package com.stitchable.api;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated by RoboPojo -- not used
 */
public class Params{

	@JsonProperty("shop_id")
	private String shopId;

	public String getShopId(){
		return shopId;
	}
}