package com.stitchable.api;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Generated by RoboPojo Generator
 * Contains results from Etsy API
 */
public class ResultsItem{

	@JsonProperty("vacation_autoreply")
	private Object vacationAutoreply;

	@JsonProperty("is_direct_checkout_onboarded")
	private boolean isDirectCheckoutOnboarded;

	@JsonProperty("is_using_structured_policies")
	private boolean isUsingStructuredPolicies;

	@JsonProperty("is_opted_in_to_buyer_promise")
	private boolean isOptedInToBuyerPromise;

	@JsonProperty("last_updated_tsz")
	private int lastUpdatedTsz;

	@JsonProperty("is_shop_us_based")
	private boolean isShopUsBased;

	@JsonProperty("is_calculated_eligible")
	private boolean isCalculatedEligible;

	@JsonProperty("title")
	private String title;

	@JsonProperty("include_dispute_form_link")
	private boolean includeDisputeFormLink;

	@JsonProperty("currency_code")
	private String currencyCode;

	@JsonProperty("has_onboarded_structured_policies")
	private boolean hasOnboardedStructuredPolicies;

	@JsonProperty("policy_shipping")
	private Object policyShipping;

	@JsonProperty("digital_listing_count")
	private int digitalListingCount;

	@JsonProperty("image_url_760x100")
	private String imageUrl760x100;

	@JsonProperty("digital_sale_message")
	private String digitalSaleMessage;

	@JsonProperty("upcoming_local_event_id")
	private Object upcomingLocalEventId;

	@JsonProperty("policy_privacy")
	private Object policyPrivacy;

	@JsonProperty("policy_seller_info")
	private String policySellerInfo;

	@JsonProperty("announcement")
	private String announcement;

	@JsonProperty("sale_message")
	private String saleMessage;

	@JsonProperty("languages")
	private List<String> languages;

	@JsonProperty("has_unstructured_policies")
	private boolean hasUnstructuredPolicies;

	@JsonProperty("is_vacation")
	private boolean isVacation;

	@JsonProperty("num_favorers")
	private int numFavorers;

	@JsonProperty("shop_name")
	private String shopName;

	@JsonProperty("policy_additional")
	private Object policyAdditional;

	@JsonProperty("url")
	private String url;

	@JsonProperty("listing_active_count")
	private int listingActiveCount;

	@JsonProperty("policy_welcome")
	private Object policyWelcome;

	@JsonProperty("shop_id")
	private int shopId;

	@JsonProperty("login_name")
	private String loginName;

	@JsonProperty("accepts_custom_requests")
	private boolean acceptsCustomRequests;

	@JsonProperty("policy_refunds")
	private String policyRefunds;

	@JsonProperty("user_id")
	private int userId;

	@JsonProperty("vacation_message")
	private Object vacationMessage;

	@JsonProperty("creation_tsz")
	private int creationTsz;

	@JsonProperty("icon_url_fullxfull")
	private String iconUrlFullxfull;

	@JsonProperty("policy_updated_tsz")
	private int policyUpdatedTsz;

	@JsonProperty("policy_payment")
	private Object policyPayment;

	@JsonProperty("policy_has_private_receipt_info")
	private boolean policyHasPrivateReceiptInfo;

	@JsonProperty("custom_shops_state")
	private int customShopsState;

	/**
	 * Gets custom shops state.
	 *
	 * @return the custom shops state
	 */
	public int getCustomShopsState() {
		return customShopsState;
	}

	/**
	 * Get vacation autoreply object.
	 *
	 * @return the object
	 */
	public Object getVacationAutoreply(){
		return vacationAutoreply;
	}

	/**
	 * Is is direct checkout onboarded boolean.
	 *
	 * @return the boolean
	 */
	public boolean isIsDirectCheckoutOnboarded(){
		return isDirectCheckoutOnboarded;
	}

	/**
	 * Is is using structured policies boolean.
	 *
	 * @return the boolean
	 */
	public boolean isIsUsingStructuredPolicies(){
		return isUsingStructuredPolicies;
	}

	/**
	 * Is is opted in to buyer promise boolean.
	 *
	 * @return the boolean
	 */
	public boolean isIsOptedInToBuyerPromise(){
		return isOptedInToBuyerPromise;
	}

	/**
	 * Get last updated tsz int.
	 *
	 * @return the int
	 */
	public int getLastUpdatedTsz(){
		return lastUpdatedTsz;
	}

	/**
	 * Is is shop us based boolean.
	 *
	 * @return the boolean
	 */
	public boolean isIsShopUsBased(){
		return isShopUsBased;
	}

	/**
	 * Is is calculated eligible boolean.
	 *
	 * @return the boolean
	 */
	public boolean isIsCalculatedEligible(){
		return isCalculatedEligible;
	}

	/**
	 * Get title string.
	 *
	 * @return the string
	 */
	public String getTitle(){
		return title;
	}

	/**
	 * Is include dispute form link boolean.
	 *
	 * @return the boolean
	 */
	public boolean isIncludeDisputeFormLink(){
		return includeDisputeFormLink;
	}

	/**
	 * Get currency code string.
	 *
	 * @return the string
	 */
	public String getCurrencyCode(){
		return currencyCode;
	}

	/**
	 * Is has onboarded structured policies boolean.
	 *
	 * @return the boolean
	 */
	public boolean isHasOnboardedStructuredPolicies(){
		return hasOnboardedStructuredPolicies;
	}

	/**
	 * Get policy shipping object.
	 *
	 * @return the object
	 */
	public Object getPolicyShipping(){
		return policyShipping;
	}

	/**
	 * Get digital listing count int.
	 *
	 * @return the int
	 */
	public int getDigitalListingCount(){
		return digitalListingCount;
	}

	/**
	 * Get image url 760 x 100 string.
	 *
	 * @return the string
	 */
	public String getImageUrl760x100(){
		return imageUrl760x100;
	}

	/**
	 * Get digital sale message string.
	 *
	 * @return the string
	 */
	public String getDigitalSaleMessage(){
		return digitalSaleMessage;
	}

	/**
	 * Get upcoming local event id object.
	 *
	 * @return the object
	 */
	public Object getUpcomingLocalEventId(){
		return upcomingLocalEventId;
	}

	/**
	 * Get policy privacy object.
	 *
	 * @return the object
	 */
	public Object getPolicyPrivacy(){
		return policyPrivacy;
	}

	/**
	 * Get policy seller info string.
	 *
	 * @return the string
	 */
	public String getPolicySellerInfo(){
		return policySellerInfo;
	}

	/**
	 * Get announcement string.
	 *
	 * @return the string
	 */
	public String getAnnouncement(){
		return announcement;
	}

	/**
	 * Get sale message string.
	 *
	 * @return the string
	 */
	public String getSaleMessage(){
		return saleMessage;
	}

	/**
	 * Get languages list.
	 *
	 * @return the list
	 */
	public List<String> getLanguages(){
		return languages;
	}

	/**
	 * Is has unstructured policies boolean.
	 *
	 * @return the boolean
	 */
	public boolean isHasUnstructuredPolicies(){
		return hasUnstructuredPolicies;
	}

	/**
	 * Is is vacation boolean.
	 *
	 * @return the boolean
	 */
	public boolean isIsVacation(){
		return isVacation;
	}

	/**
	 * Get num favorers int.
	 *
	 * @return the int
	 */
	public int getNumFavorers(){
		return numFavorers;
	}

	/**
	 * Get shop name string.
	 *
	 * @return the string
	 */
	public String getShopName(){
		return shopName;
	}

	/**
	 * Get policy additional object.
	 *
	 * @return the object
	 */
	public Object getPolicyAdditional(){
		return policyAdditional;
	}

	/**
	 * Get url string.
	 *
	 * @return the string
	 */
	public String getUrl(){
		return url;
	}

	/**
	 * Get listing active count int.
	 *
	 * @return the int
	 */
	public int getListingActiveCount(){
		return listingActiveCount;
	}

	/**
	 * Get policy welcome object.
	 *
	 * @return the object
	 */
	public Object getPolicyWelcome(){
		return policyWelcome;
	}

	/**
	 * Get shop id int.
	 *
	 * @return the int
	 */
	public int getShopId(){
		return shopId;
	}

	/**
	 * Get login name string.
	 *
	 * @return the string
	 */
	public String getLoginName(){
		return loginName;
	}

	/**
	 * Is accepts custom requests boolean.
	 *
	 * @return the boolean
	 */
	public boolean isAcceptsCustomRequests(){
		return acceptsCustomRequests;
	}

	/**
	 * Get policy refunds string.
	 *
	 * @return the string
	 */
	public String getPolicyRefunds(){
		return policyRefunds;
	}

	/**
	 * Get user id int.
	 *
	 * @return the int
	 */
	public int getUserId(){
		return userId;
	}

	/**
	 * Get vacation message object.
	 *
	 * @return the object
	 */
	public Object getVacationMessage(){
		return vacationMessage;
	}

	/**
	 * Get creation tsz int.
	 *
	 * @return the int
	 */
	public int getCreationTsz(){
		return creationTsz;
	}

	/**
	 * Get icon url fullxfull string.
	 *
	 * @return the string
	 */
	public String getIconUrlFullxfull(){
		return iconUrlFullxfull;
	}

	/**
	 * Get policy updated tsz int.
	 *
	 * @return the int
	 */
	public int getPolicyUpdatedTsz(){
		return policyUpdatedTsz;
	}

	/**
	 * Get policy payment object.
	 *
	 * @return the object
	 */
	public Object getPolicyPayment(){
		return policyPayment;
	}

	/**
	 * Is policy has private receipt info boolean.
	 *
	 * @return the boolean
	 */
	public boolean isPolicyHasPrivateReceiptInfo(){
		return policyHasPrivateReceiptInfo;
	}
}